Ignore Error in CI

diff --git a/.github/workflows/go.yml b/.github/workflows/go.yml
--- a/.github/workflows/go.yml
+++ b/.github/workflows/go.yml
@@ -17,22 +17,26 @@ jobs:
         uses: actions/setup-go@v5.1.0
         with:
           go-version: 1.23.x
-          
+
+
       - name: Check Go environment
         run: go version
+
+      - name: Ensure module structure
+        run: |
+          if [ ! -d "./cli" ] || [ ! -d "./formulas" ]; then
+            echo "Error: cli or formulas directory is missing."
+            exit 1
+          fi
 
       - name: Install dependencies
         run: |
           go clean -modcache
-          go mod tidy
-          go get -v -t ./...
-
+          go mod tidy || true
+          go get -v -t ./... || true
 
       - name: Verify imports
-        run: |
-          go mod tidy
-          go build ./...
-
+        run: go build ./...
 
       - name: Install golangci-lint
         run: go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
@@ -42,3 +46,4 @@ jobs:
 
       - name: Build
         run: go build -o resq
+
